# Generated by Django 5.0.7 on 2024-09-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("firstName", models.CharField(max_length=50)),
                ("lastName", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubmitFrontendData",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("sociogramId", models.CharField(max_length=100)),
                ("firstName", models.CharField(max_length=50)),
                ("lastName", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("posQuestions", models.JSONField(default=list)),
                ("negQuestions", models.JSONField(default=list)),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="answers_frontend", to="api.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sociogram",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("instructorName", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("language", models.CharField(max_length=2)),
                ("negQuestions", models.JSONField()),
                ("posQuestions", models.JSONField()),
                ("publishedUsers", models.JSONField(blank=True, default=list)),
                (
                    "users",
                    models.ManyToManyField(related_name="sociograms", to="api.user"),
                ),
            ],
        ),
    ]
